name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install prod dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/prod.txt ]; then pip install -r requirements/prod.txt; fi
    - name: Check for flake8
      run: |
        if python -c "import flake8" &> /dev/null; then
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        else
          echo "flake8 is not installed, skipping linting."
        fi
